# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: <%= packageJSON.name %> # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512
  region: us-west-2

functions:
  serveBoringApp:
    timeout: 900  # this is the max lambda timeout, which will work if it's triggeed by a ALB.  API gateway requests clamp to 30 seconds
    handler: handler.serveBoringApp
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      NODE_ENV: production
      boring_express_noopListen: true # this tells express not to call app.listen
