version: '3'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redis
  dynamodb:
    image: instructure/dynamo-local-admin
    ports:
      - "8000:8000"
  haproxy:
    image: haproxy:1.5
    volumes:
      - ./config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./config/haproxy/selfsigned.combined.pem:/etc/ssl/private/selfsigned.combined.pem
    ports:
      - "443:443"
      - "80:80"

networks:
  redis:
    driver: bridge