version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redis
  dynamodb:
    image: instructure/dynamo-local-admin
    ports:
      - "8000:8000"  
  haproxy:
    image: haproxy:1.5
    volumes: 
      - ./config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./config/haproxy/new2me.combined.pem:/etc/ssl/private/new2me.combined.pem
    ports:
      - "443:443"
      - "80:80"

networks:
  redis:
    driver: bridge